Move input unit conversion and bounds checking to base class
karllark/dust_extinction pull request #240
Opened 2024-09-05 16:37 UTC by lpsinger

2024-09-05 18:59 UTC, karllark commented
Please add a description to this PR to describe in words the goal.  Thanks.

2024-09-05 19:00 UTC, karllark commented
Please add a description to this PR to describe in words the goal.  Thanks.

2024-09-05 19:07 UTC, lpsinger commented
> Please add a description to this PR to describe in words the goal. Thanks.

Done.

2024-09-13 13:10 UTC, karllark requested changes
This is a a really nice PR.  Really neat to see how to use the astropy modeling machinery to get the units in x right.  Thanks for putting it in.

2024-09-13 13:10 UTC, karllark commented on docs/dust_extinction/dev_model.rst
> +* A member function `evaluate` that computes the extinction at a given `x` and any model parameter values.  The `x` values are checked to be within the valid `x_range`. The `x` values passed to the `
Please change "have not units" to "do not have units."

2024-09-13 13:10 UTC, karllark commented on dust_extinction/averages.py
> +    @classmethod
Can you explain the benefit of adding the `@classmethod` for all the evaluate functions?  I've not used this before and my reading docs has not made this clear.  Likely I'm just being a bit dense - thanks in advance for an explanation.

2024-09-13 13:10 UTC, karllark commented on dust_extinction/helpers.py
> +        "x has no units, assuming x units are inverse microns", UserWarning
Should this be using `SpectralUnitsWarning` introduced in PR #239?

2024-09-13 13:33 UTC, lpsinger commented on dust_extinction/helpers.py
> +        "x has no units, assuming x units are inverse microns", UserWarning
Fixed.

2024-09-13 13:33 UTC, lpsinger commented on docs/dust_extinction/dev_model.rst
> +* A member function `evaluate` that computes the extinction at a given `x` and any model parameter values.  The `x` values are checked to be within the valid `x_range`. The `x` values passed to the `
That was a typo, which I have fixed. I meant "have no units." Do you prefer "do not have units?"

2024-09-13 13:34 UTC, lpsinger commented on dust_extinction/averages.py
> +    @classmethod
You had several `@classmethod` evaluate methods in averages.py. I was just trying to make it consistent where the evaluate methods don't actually reference self.

There's probably no performance benefit, it's just a style thing.

2024-09-13 14:17 UTC, karllark commented on dust_extinction/averages.py
> +    @classmethod
I'm fine with this.  Thanks for the info.

2024-09-13 14:17 UTC, karllark commented on docs/dust_extinction/dev_model.rst
> +* A member function `evaluate` that computes the extinction at a given `x` and any model parameter values.  The `x` values are checked to be within the valid `x_range`. The `x` values passed to the `
"have no units" is fine.

2024-09-16 12:41 UTC, karllark approved these changes
Looks great.   Thanks!

2024-09-16 12:41 UTC, merged